project:
  type: manuscript
  render:
  - "!notebooks/proteomics/"
  - "!notebooks/qPCR/old_qPCR_import/"

execute:
  freeze: false

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  pdf: default